### ISSUE TITLE
Source code for site?

### ISSUE THREAD

**Issue by cvan** [facebookincubator/react-vr#10]
I see the `.html` files in the `gh-pages` branch, but not any source files (e.g., `.md` files) in `master`.

1. Load https://facebookincubator.github.io/react-vr/docs/dev-tools.html
2. Scroll to the bottom and find `You can edit the content above on GitHub and send us a pull request!`
3. Click the [`edit the content above on GitHub` link](https://github.com/facebookincubator/react-vr/blob/master/docs/DevTools.md)
4. Notice, it 404s because the original Markdown files are not in `master`

**Comment by mikearmstrong001** [comment]
Thanks, we should remove this until we are ready to accept the pull requests. I'll make that change.

@cvan was there a particular problem you wanted to address ? Maybe you could detail it here.

**Comment by mikearmstrong001** [comment]
The website has been update to remove the link and avoid any confusion but please reopen if there is a specific problem you feel we should address.

As this is a preview release which will help us to firm up the new apis, we have not placed the source code into GitHub. We do expect to make changes based on feedback, we will then stabalize and after this point we will fully Open Source and accept PRs. The md files will be going into the repo when we fully Open Source

**Comment by cvan** [comment]
@mikearmstrong001, thanks for your response and for updating the site.

Setting aside my organisation affiliation, I'm truly very excited about React VR. Since its inception in 2014, the WebVR space has been about sharing and collaborating. I really do want the Web, as a development environment and distribution channel, to be the best platform for delivering VR experiences. With that being said, feel free to read my suggestions and thoughts I just wrote on the issue of React VR's codebase during this alpha public release: https://github.com/facebookincubator/react-vr/issues/13#issuecomment-267564678

By the way, huge congratulations! Reading the docs and tinkering with the samples have given me nothing but hope and excitement for the future❗️🎉
