### ISSUE TITLE
It was not obvious that the samples folder existed

### ISSUE THREAD

**Issue by Fasani** [facebookincubator/react-vr#12]
Documentation could be improved to talk more about how to access the 'Samples' as it may be missed.
http://localhost:8081/Samples/

I manually installed these as I thought they are needed.
npm install -g react-native-cli
npm install -g npm-cli

Then I get this error:
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! @ start: `node node_modules/react-native/local-cli/cli.js start --root .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'node node_modules/react-native/local-cli/cli.js start --root .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/react-native/local-cli/cli.js start --root .
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:

Support File:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 verbose lifecycle @~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle @~prestart: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\Github\react-vr\node_modules\.bin;C:\Users\Fasani\AppData\Local\GitHub\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\cmd;C:\Users\Fasani\AppData\Local\GitHub\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\usr\bin;C:\Users\Fasani\AppData\Local\GitHub\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\usr\share\git-tfs;C:\Users\Fasani\AppData\Local\Apps\2.0\TQ2WCTZX.CX4\E3VNEB33.2W8\gith..tion_317444273a93ac29_0003.0003_665ccbdbd3c2d8d4;C:\Users\Fasani\AppData\Local\GitHub\lfs-amd64_1.3.1;C:\Users\Fasani\AppData\Local\Apps\2.0\TQ2WCTZX.CX4\E3VNEB33.2W8\gith..tion_317444273a93ac29_0003.0003_665ccbdbd3c2d8d4\NativeBinaries\x86;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\Fasani\AppData\Roaming\npm;C:\Program Files (x86)\HMA! Pro VPN\bin;C:\Users\Fasani\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\MSBuild\14.0\bin\;C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\x64
8 verbose lifecycle @~prestart: CWD: E:\Github\react-vr
9 silly lifecycle @~prestart: Args: [ '/d /s /c',
9 silly lifecycle   'node -e "try{require(\'fs\').statSync(\'node_modules\')}catch(e){process.exit(1)}" || npm install' ]
10 silly lifecycle @~prestart: Returned: code: 0  signal: null
11 info lifecycle @~start: @
12 verbose lifecycle @~start: unsafe-perm in lifecycle true
13 verbose lifecycle @~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\Github\react-vr\node_modules\.bin;C:\Users\Fasani\AppData\Local\GitHub\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\cmd;C:\Users\Fasani\AppData\Local\GitHub\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\usr\bin;C:\Users\Fasani\AppData\Local\GitHub\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\usr\share\git-tfs;C:\Users\Fasani\AppData\Local\Apps\2.0\TQ2WCTZX.CX4\E3VNEB33.2W8\gith..tion_317444273a93ac29_0003.0003_665ccbdbd3c2d8d4;C:\Users\Fasani\AppData\Local\GitHub\lfs-amd64_1.3.1;C:\Users\Fasani\AppData\Local\Apps\2.0\TQ2WCTZX.CX4\E3VNEB33.2W8\gith..tion_317444273a93ac29_0003.0003_665ccbdbd3c2d8d4\NativeBinaries\x86;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\Fasani\AppData\Roaming\npm;C:\Program Files (x86)\HMA! Pro VPN\bin;C:\Users\Fasani\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\MSBuild\14.0\bin\;C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\x64
14 verbose lifecycle @~start: CWD: E:\Github\react-vr
15 silly lifecycle @~start: Args: [ '/d /s /c',
15 silly lifecycle   'node node_modules/react-native/local-cli/cli.js start --root .' ]
16 silly lifecycle @~start: Returned: code: 1  signal: null
17 info lifecycle @~start: Failed to exec start script
18 verbose stack Error: @ start: `node node_modules/react-native/local-cli/cli.js start --root .`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
18 verbose stack     at emitTwo (events.js:87:13)
18 verbose stack     at EventEmitter.emit (events.js:172:7)
18 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
18 verbose stack     at emitTwo (events.js:87:13)
18 verbose stack     at ChildProcess.emit (events.js:172:7)
18 verbose stack     at maybeClose (internal/child_process.js:821:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
19 verbose pkgid @
20 verbose cwd E:\Github\react-vr
21 error Windows_NT 10.0.14393
22 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
23 error node v5.4.0
24 error npm  v3.3.12
25 error code ELIFECYCLE
26 error @ start: `node node_modules/react-native/local-cli/cli.js start --root .`
26 error Exit status 1
27 error Failed at the @ start script 'node node_modules/react-native/local-cli/cli.js start --root .'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the  package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     node node_modules/react-native/local-cli/cli.js start --root .
27 error You can get their info via:
27 error     npm owner ls
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]

**Comment by mikearmstrong001** [comment]
Thanks for your feedback, we'll have a look that section and try and improve it.

Just to confirm this was the documentation as opposed to the blog post?

**Comment by Fasani** [comment]
Yes the github read me. It was late last night not sure what these errors are connected too and I didn't have more time to spend.

**Comment by amberroy** [comment]
The github readme now clarifies the contents of the pre-release including samples.  The recommended way to get React VR is to download the pre-release zip (linked in the readme), extract and then run "npm install" from there.

**Comment by Fasani** [comment]
Hey I just checked the readme and it points people to:

http://localhost:8081/vr/
Which returns:
Cannot GET /vr/

It should point people to
http://localhost:8081/Samples/

**Comment by Fasani** [comment]
Oh also a fresh install and today I have no issues. I am able to browse and play with /Samples folder.

**Comment by Fasani** [comment]
Not sure if commenting here is seen I will post a new issue.
