### ISSUE TITLE
Add `git clone` instructions to "Getting Started" docs

### ISSUE THREAD

**Issue by cvan** [facebookincubator/react-vr#13]
https://facebookincubator.github.io/react-vr/docs/getting-started.html

**Comment by andrewimm** [comment]
Sorry, what would you like to clone? There is no code repo right now.

**Comment by cvan** [comment]
> Sorry, what would you like to clone? There is no code repo right now.

When will the React VR code be open-sourced? I'd think if there are docs for usage, folks would want to look at the source code. I'm reading minified source code in my Dev Tools right now to figure out how things are working.

**Comment by cvan** [comment]
I can just look at the source of the files in my `node_modules/`, but I'm still curious since the code is being published on `npm` that the source code isn't on GitHub for the React VR code nor the Docs.

**Comment by andrewimm** [comment]
What you're seeing now is a limited developer preview of React VR, and we are not ready to Open Source it yet. We want to collect developer feedback on the APIs and experience we currently provide, and have a more stable 1.0 target before opening things up fully on GitHub.

The biggest challenge of initially open sourcing a project – in my opinion – is having a codebase that is ready for external contribution, and that's something we're not ready for yet. We don't want people to sink in a bunch of time building on internal APIs that are going to change in the near future, so please bear with us while we continue developing towards that milestone. With the community's input, we should hopefully be able to reach that goal in the next few months.

**Comment by cvan** [comment]
Thanks for the response. And congrats on the launch - this is another truly significant milestone for WebVR.

I mean the following comments with the utmost sincerity and respect. As the source code is being released through `npm`, it's already public source code. By not publishing the source code on GitHub, developers can and will be deterred from exploration and early adoption. I'm very curious, excited, and optimistic by React VR. I'm just a bit thrown off that I have to dig through source maps in my Developer Tools and look in my `node_modules/` directory to debug what's going on.

Approachability is key. Developer ergonomics need to be solid enough that developers feel not only they can identify value in the product but also that there's peace of mind in investing any time tinkering or using React VR in any capacity (professionally or hobby-wise).

Personally, I feel a strong desire that we ought to be held to a higher standard than competing closed vertical solutions for adhering to the fair principles of the Web with anything introduced in the WebVR space. Especially with Facebook's (deserving) influence with the React brand, any WebVR tools introduced to developers should be seen by professionals as inviting improvements to an already accessible, open platform.

> We don't want people to sink in a bunch of time building on internal APIs that are going to change in the near future, so please bear with us while we continue developing towards that milestone.

I'm being genuine when I say this: from what I've seen in past projects and other open-source projects, there will be more time sunk into people trying to reverse-engineer and having to fumble around to introspect the source code, regardless.

Tomorrow, the question might be, "How can developers help React VR?" But, today, the question developers likely want answered is, "How can React VR help developers?"

> With the community's input, we should hopefully be able to reach that goal in the next few months.

Transparency is going to only help improve React VR. Holding back on releasing the source code cannot improve the product in any meaningful way. I'm not sure how folks can provide valuable input or ask well-informed questions without having source code to refer to when posting issues.

Having the project's source code easily accessible does not necessarily necessitate an invitation to design by committee. In fact, it's a testament to Facebook's commitment to open-source software if React VR wants to involve the community in the _process_, not the _product_, of a WebVR framework.

At the very least, if the React VR team isn't comfortable (regardless of product or engineering reasons) in the near term with publishing the source code on GitHub, I'd suggest first reconsidering or at the very least consideration of these suggestions:

1. Publish to this GitHub repo the code that's already published on [`npm` from the `react-vr` module](https://www.npmjs.com/package/react-vr) (and is also available as a [`.tgz` download from the `npm` API](https://registry.npmjs.org/react-vr/-/react-vr-0.1.1.tgz)).
2. Publish to this GitHub repo the Markdown files for the site docs (e.g., for [this page](https://facebookincubator.github.io/react-vr/docs/getting-started.html). (I've noticed a few typos and improved docs changes that would make for helpful PRs, but I've noticed the footer links to edit the docs pages have been removed. The Markdown files aren't on GitHub anyway, only the generated `.html` files are. That means there's nothing I can do but file an issue which will requier involve manual intervention and eventual fixing by Facebook's core React VR team.)
3. Release the React VR source code to a closed (invite-only?) alpha group, wherein folks can freely, easily peruse the codebase, provide input, and receive troubleshooting help on React VR's API as well as its current and desired usage and applications.
4. Create and release several more comprehensive code samples and boilerplates for folks to understand the use cases, strengths, limitations, and best practices of not only React VR but of WebVR.

With the many moving parts (e.g., differences in headsets, browsers, operating systems, library dependencies, polyfills, user error, developer error), diagnosing issues in the WebVR space is already a challenge. Not being able to have folks point one another to a line of code in question is going to complicate the complexity of what we're all trying to build towards: WebVR being a premier platform for delivering VR experiences.

Apologies if this message comes across as my being pedantic or persistent. I want to ensure that we all, as pioneering and passionate participants in the exciting WebVR space, set a precedent of transparency and developer respect. I'll go out on a limb and say that these are our responsibilities, as browser vendors and framework makers, if we want WebVR – not only our frameworks, for example – to succeed.

**Comment by mikearmstrong001** [comment]
@cvan thanks for your thoughts.

I think you understand our immediate position. It is our every intention to get everything out as a full source repo but this will not happen by the end of 2016, I do expect very early 2017 and we don't anticipate a drawn out timeframe.

Prior to going to GitHub there are some areas we know we want to address and by not yet releasing to GitHub we hope to indicate that level of expectation to the early users. We are not ready to accept PRs because of this. As a team we kicked around several ways to open up our work as early as possible and we determined that full source via npm but not on GitHub would offer the best compromise between setting expectation and yet still allowing users to develop, debug and provide feedback.

Expect your point 1, 2 and 4 to happen in stages in 2017. Whether 3 needs to happen will be determined based on data we gather from this prerelease.

Please understand where we are coming from, if you can work within these constraints and still provide this level of feedback it would be much appreciated, it helps us. It won't be long.
