### ISSUE TITLE
500 error while trying to load the bundle file. 

### ISSUE THREAD

**Issue by MickyCook** [facebookincubator/react-vr#16]
**Description**
The error occurred after installing React VR from the press release preview and also while trying the create project via the react-vr-cli. I also tried npm run bundle on the default install (Terminal error message below). 

**errors:**
* console: 
http://localhost:8081/vr/client.bundle?platform=vr 500 (Internal Server Error)
* asset url in browser: 
Unknown option: /Users/mickycook/node_modules/react-server/target/server/server.js.RootContainer. Check out http://babeljs.io/docs/usage/options/ for more information about options.\n\nA common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:\n\nInvalid:\n  `{ presets: [{option: value}] }`\nValid:\n  `{ presets: [['presetName', {option: value}]] }`\n\nFor more detailed information on preset configuration, please see http://babeljs.io/docs/plugins/#pluginpresets-options.
* terminal: 
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "bundle"
npm ERR! node v6.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! VR@0.0.1 bundle: `node node_modules/react-vr/scripts/bundle.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the VR@0.0.1 bundle script 'node node_modules/react-vr/scripts/bundle.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the VR package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/react-vr/scripts/bundle.js
npm ERR! You can get information on how to open an issue fo

### Additional Information

* npm version: 4.0.5
* node version: v6.4.0
* Operating System: [MacOS El Capitan]
* Browser: [Chrome]

**Comment by andrewimm** [comment]
This mentions a node module called `react-server`, which is not part of our project. Are you sure you don't have another server currently running on port :8081?

**Comment by MickyCook** [comment]
I'm positive I do not. I tried it on my other computer and it works fine so I'll close this issue and keep looking into the problem on the problematic machine.
