### ISSUE TITLE
Positioning relative to the camera orientation?

### ISSUE THREAD

**Issue by borisyankov** [facebookincubator/react-vr#19]
Is there any way currently, to position a component in the center of screen (always)?
I want to render a gaze cursor.

**Comment by mikearmstrong001** [comment]
A bit of requirement gathering.

We do have a gaze cursor built in, which you can enable using something like this (from the tour sample)

```
  const vr = new VRInstance(bundle, 'TourSample', parent, {
    // Show a gaze cursor.
    cursorEnabled: true,
    ...options,
  });
```

You can also control if it autohides when not over something that is interactive via `cursorAutoHide: bool` in the same VRInstance options object.

This will enable the cursor when on mobile or in VR but not on desktop and this is purposeful as in that case we default controls to the mouse pointer.

If you want to handle you own gaze cursor then I'd suggest you don't handle the rendering within the React VR code. The reason for this is that the React VR code runs asynchronously in the a webwork and for a gaze cursor you want this pinned to the camera, lag is really not desired. To do this you will want to make use of the render function of the VRInstance, see the CubeSample client.js for an example. I can put together a small demo of this over the weekend.

Does this help?

**Comment by borisyankov** [comment]
Yeah, helps a ton! Thanks.

**Comment by mikearmstrong001** [comment]
Please feel free to reopen if you need more information

**Comment by nikosantoro** [comment]
Hi guys, do you have any working example of Gze Pointer in react-vr app?
