### ISSUE TITLE
Document navigation have button spots switched

### ISSUE THREAD

**Issue by TonOfPrince** [facebookincubator/react-vr#2]
### Description
The prev and next buttons in the docs are switched.

#### Expected behavior
At the bottom of a page, the next button should be on the right and the prev button on the left.

#### Actual behavior
At the bottom of a page, the next button is on the left and the prev button on the right.

### Reproduction

Go to any page in the docs.

### Solution

Update the next and prev classes in react-native/css/react-native.css to be:

```
.docs-prev {
  float: left;
}

.docs-next {
  float: right;
}
```

### Additional Information

* React VR version: react-vr
* Operating System: MacOS
* Graphics Card: [FILL THIS OUT: NVIDA, ATI, Intel? Which Driver?]
* Browser: Chrome, and Safari
* VR Device: Out of VR (in documentation)
<img width="696" alt="screen shot 2016-12-13 at 10 57 07 pm" src="https://cloud.githubusercontent.com/assets/4095485/21169134/850fa9b8-c187-11e6-9f18-70b3d0961db4.png">

**Comment by mikearmstrong001** [comment]
Thank you for the report.

it looks like we took the scripts from react native at a time when they were swapped in https://github.com/facebook/react-native/commit/1ceb2f7519862c5e37a6b0e80aa4fec95cd28e52

Fix has been made for future doc generation

**Comment by mikearmstrong001** [comment]
fixed in online docs
https://facebookincubator.github.io/react-vr
