### ISSUE TITLE
Smartphone + Google Cardboard Support Missing

### ISSUE THREAD

**Issue by johnnyshankman** [facebookincubator/react-vr#22]
### Description

Feature: Ability to use Google Cardboard + iPhone as VR headset with `react-vr`.

#### Expected behavior

Given I am not yet wearing any set
And I intend on using Google Cardboard
When I tap on the "View in VR" button
I should see the screen switch to stereoscopic rendering
And I should also be shown the dismissible `SupportMessage`

#### Actual behavior

I am shown the `SupportMessage` and stuck in Augmented Reality on my phone browser.

### Reproduction

Open the sample project on an iPhone in Safari and click the "View in VR"  button.

### Solution

Using `Three.StereoEffect` as a fallback VR effect in `Player.js` and allowing for users to toggle between AR and simple stereoscopic VR effect. 

The AR accelerometer tracking already works great, so by simply adding the stereoscopic effect a user could throw their phone in cardboard and feel immersed.

I've used the following before succesfully:
```
effect = new THREE.StereoEffect(renderer); 
effect.render(scene, camera);
```

It even has its own [npm module](https://www.npmjs.com/package/three-stereo-effect) right now

### Additional Information

* react-vr package version: most recent 0.1.1
* react-vr-web package version: 0.1.1
* Operating System: Mac OSX El Capitan for Dev / iOS10 for Phone
* Graphics Card: iPhone 7 A9 chip i think?
* Browser: Latest Chrome and Safari for iOS10
* VR Device: Google Cardboard + iPhone

**Comment by johnnyshankman** [comment]
A related issue would be that it is unclear where, when, or if we are allowed access to the renderer in order to add rendering effects and global shaders.

**Comment by andrewimm** [comment]
Right now we are only shipping support for the official WebVR API, which is being developed by a consortium of browser vendors. Chrome recently released their beta version of this API, and it works well with cardboard headsets, so this stuff is coming very soon. As these APIs roll out to stable browsers, we are going to let browsers control how true VR content is displayed at a system level.

However I would agree that it would be good to have access to override the player's rendering effect with something of your own. I'll explore whether there is a way to reliably expose this, or whether it is too deep within OVRUI to reliably control.
