### ISSUE TITLE
Support for stereo equirectangular panos in Pano

### ISSUE THREAD

**Issue by delavara** [facebookincubator/react-vr#24]
Hi all,

I'm having a lot of fun playing with react-vr! 

One question, is there/will there be Pano support for rendering stereo equirectangular images in the future?

I tried using the following image with all different the different options for the `source` prop but no luck. 
![stereo_equirect](https://cloud.githubusercontent.com/assets/1102619/21278461/4f4e78a8-c3a9-11e6-9160-1155b85a556b.jpg)

Thanks!
Cody

**Comment by mikearmstrong001** [comment]
@delavara to confirm we will be support this stereo format as well as other mono and stereo texture formats

will update again when we land the changes

**Comment by delavara** [comment]
@mikearmstrong001 thanks for the zippy response Mike. That sounds good, looking forward to it!

**Comment by mikearmstrong001** [comment]
No problem and glad you enjoying playing with it.
Let's leave open till it lands :)

**Comment by lruminski** [comment]
There still seems to be lack of stereoscopic support in v1.1.0 (the latest).
I'm just seeing the 2 images side-by-side.

**Comment by lruminski** [comment]
it works when i specify {uri, stereo} but not {asset, stereo}

**Comment by moroneyk** [comment]
Same issue for me, it works when i specify {uri, stereo} but not {asset, stereo}

**Comment by jprucey** [comment]
The stereoscopic image is blurry, the normal pano looks fine
