### ISSUE TITLE
How to start on custom IP

### ISSUE THREAD

**Issue by MrEfrem** [facebookincubator/react-vr#3]
### Description

How specified custom IP address for start development server?
I development in MacOS therefore need to launch browser in Windows on VirtualBox.

#### Expected behavior

Dev server started on custom IP address.

#### Actual behavior

Dev server only started on localhost:8081.

### Additional Information

* React VR version: react-vr-web
* Operating System: MacOS
* Graphics Card: Intel
* Browser: Firefox nightly
* VR Device: Out of VR

**Comment by MrEfrem** [comment]
I solved a problem. It appears React-native is launched on all accesses IP.

**Comment by amberroy** [comment]
Glad you solved it!  If you do need to start on a custom IP address you can start the server manually, using the command for "start" in `package.json` and adding the `--host` flag for example:
```node node_modules/react-native/local-cli/cli.js start --root . --host "localhost" ```
Replacing "localhost" with the IP.

For a list of additional options use `--help`:
```node node_modules/react-native/local-cli/cli.js start --help```

**Comment by MrEfrem** [comment]
Thank you for information.
