### ISSUE TITLE
VR Cursor Is Not Where Click Event Fires

### ISSUE THREAD

**Issue by johnnyshankman** [facebookincubator/react-vr#31]
### Description

Bug:

When looking around in AR mode on mobile with `cursorEnabled: true` the click event is oddly delegated to where the user taps on screen, not the cursor's position. Furthermore, the `onClick` handler only reliably happens when the user is simultaneously hovered over the element (looking directly at it and succesfully triggered `onEnter`) with the white cursor *and* tapping directly in the center of the screen. 

This is unintuitive and seems like a bug or an oversight.

It is more intuitive for the click event to be delegated to the element currently eclipsed by the white VR cursor centered in the middle of the screen. That way someone can hover over something like a `VRButton` to trigger the `onEnter` event, and then tap anywhere on screen to trigger the `onClick` event. 

Otherwise, if they look at the element the `onEnter`will invoked but then when they tap/click on screen the `onClick` will not be invoked. This makes it incredibly difficult to figure out how to click on things while using a react-vr app.

#### Expected behavior

Given I am on mobile
And have not yet entered into VR Mode
And I have cursor enabled
When I hover over a VR element (like VRButton)
And see the `onEnter` handler execute
When I tap anywhere on screen
I expect the `onClick` handler to execute

#### Actual behavior

Given I am on mobile
And have not yet entered into VR Mode
And I have cursor enabled
When I hover over a VR element (like VRButton)
And see the `onEnter` handler execute
When I tap anywhere on screen
The `onClick` handler does not execute

When I tap directly in the center of the screen
The `onClick` handler does execute

#### Logs

N/A

### Reproduction

Open up `CubeSample` (it has `cursorEnabled` set to `true` by defaulted) on a mobile browser (I was using iOS10 Safari). Orient your phone so that you're VR cursor is hovering over the VRButton on screen and invoking the `onEnter` handler. Now tap anywhere on screen besides the direct center. The `onClick` handler which changes the color is not invoked. I

To get the onClick to invoke you must hover over the element *and* press directly in the center of the screen.

### Solution

Divert the click event to the element I have entered/hovered on aka the element being directly looked at in the middle of the screen and eclipsed by the white dot.

### Additional Information

* react-vr package version: 0.1.1
* react-vr-web package version: 3.10.9
* Operating System: OSX/iOS10
* Graphics Card: iPhone
* Browser: Safari and Chrome for iOS10
* VR Device: Technically none. Just a mobile phone. A desktop simulating mobile would also suffice.

**Comment by amberroy** [comment]
Currently this is the intended behavior, because when there is no cursor we wanted the "finger tap" event to fire on the item under your finger, not the center of the screen.  But I can see how it's confusing with a cursor.  We'll look into this, thanks for the detailed feedback.

**Comment by johnnyshankman** [comment]
@amberroy great! Yeah this would open the door for cardboard-type stuff working well too, as that random click in the corner you get by pressing in on the corner of the cardboard can always be rerouted to the cursor in the middle of the screen!

**Comment by amberroy** [comment]
Touch event now fires at object under cursor, not at tap location on screen.
