### ISSUE TITLE
param `lit` for Mesh source is not documented

### ISSUE THREAD

**Issue by nikgraf** [facebookincubator/react-vr#32]
### Description

While `lit` is used in the Mesh example I couldn't find any documentation. I'm happy to create PR in case, but first need to understand it's purpose.

see https://facebookincubator.github.io/react-vr/docs/mesh.html#source

**Comment by mikearmstrong001** [comment]
`lit` specifies that the materials use in for the creation of meshes should work with lights.
By default lit is false and a simple unlit material is used, if lit is set to true a Phong based material is created.

We'll update the docs, thanks for the highlighting.
