### ISSUE TITLE
<Text /> Component unable to render Chinese

### ISSUE THREAD

**Issue by ju5td0m7m1nd** [facebookincubator/react-vr#35]
### Description

I tried to render Chinese with Text component, but in the canvas, words turned out to be stars

Any suggestion or solution to make it render properly ?

Thanks

#### Expected behavior

Render Chinese in Text Component

#### Actual behavior

those words turn out to be stars

#### Logs

<img width="361" alt="2016-12-28 12 12 21" src="https://cloud.githubusercontent.com/assets/12392676/21513729/f557acfa-ccf6-11e6-841a-50a1a2b96bff.png">

**Comment by mikearmstrong001** [comment]
We don't have a SDF font code page for Chinese but it is possible to generate your own SDF font which includes your required glyphs using the Oculus mobile SDK fontue tool.

More information on the approach we have taken and the tools can be found [here](https://facebookincubator.github.io/react-vr/docs/fonts.html)

We understand the limitations and we are discussing more complete codepage options for font support

**Comment by liyuechun** [comment]
http://bbs.react-vr.org
