### ISSUE TITLE
Pano with cubemap is flipped

### ISSUE THREAD

**Issue by Ninerian** [facebookincubator/react-vr#4]
### Description
When creating a pano component with an array of cubic images as input, the textures are flipped on the y axis. This is caused by the THREE.cubeTexture which sets the flipY property to false. 

#### Expected behavior
the cubic images should be shown with the correct orientation

#### Actual behavior
the cubic images are shown upside down

### Reproduction
Create a View Component with a pano component in it:
```
<View
              <Pano source={{uri: ['image_r.jpg', 'image_l.jpg', 'image_d.jpg', 'image_u.jpg', 'image_f.jpg', 'image_b.jpg']}}/>
</View>
```
On rendering the error should be seen.

### Solution
In the class `RCTPano`, the callback of the loading function should be changed at line 124. Adding the line 

```
texture.flipY = true;
```

will solve the problem.

### Additional Information

* React VR version: react-vr-web
* Operating System: MacOS
* Graphics Card: Nvidia
* Browser: Chromium 44.0.2383.0, Carmel
* VR Device: GearVR

**Comment by mikearmstrong001** [comment]
Thanks for reporting

To match and standardize with the texture within the three.js repo I have chosen to remove the -1 scale on X for cubemaps rather than flipping the texture.

The reason this was working for us was due to the way we were processing the example cubemap, this will now change.

fix will be in next update

**Comment by mikearmstrong001** [comment]
applied in react-vr-web-0.1.1 and react-vr-0.1.1

**Comment by Kiet-Nguyen** [comment]
I'm currently using react-360, setting 1:6 cubestrip image as the background image and experiencing the same problem: the texture on all faces is flipped on Y-axis. Could you please check?
