### ISSUE TITLE
Feature Request: Allow access to camera reference

### ISSUE THREAD

**Issue by morsdyce** [facebookincubator/react-vr#43]
### Description

Currently React VR does not give you access or allow you to create your own camera.
I think this would be pretty helpful in case we want to manipulate the "player" location.

For example I implemented basic support for VR controllers using a native module, it makes sense that in the future i'd like to move around with either full locomotion (analog sticks) or teleportation (blink mechanic).

### Solution

This can be fixed in 2 ways and should probably be implemented via both to allow maximum flexibility. 
1. Allow to pass a camera via VRInstance options object and pass it to the new Player invocation
2. Implement a function on the VRInstance class that returns the current camera.

**Comment by DilipRamirez** [comment]
this is already implemented if i'm not mistaken, although we must modify: 

initialize `this.camera = options.camera || null;` in  the `VRInstance` constructor

then pass the camera to the player in 
`this.player = new Player({
      elementOrId: parent,
      width: options.width,
      height: options.height,
      camera: this.camera,
    });`

in OVRUI/lib/Player/Player.js add
`this._camera = (options.hasOwnProperty('camera'))? options.camera : null;` 

And finally pass the camera while creating VRInstance  in client.js.  The only drawback of this "patch" is that we have to calculate manually width & height (I just copied this from Player.js' camera implementation): 

// If container not specified, default to full window.
  if (!this._el) {
    this._el = document.body;
  }
  // If height and width are not provided, detect them from the container.
  var fixedSize = true;
  if (!width) {
    if (this._el === document.body) {
      fixedSize = false;
      width = window.innerWidth;
    } else {
      width = this._el.clientWidth;
    }
  }
  if (!height) {
    if (this._el === document.body) {
      fixedSize = false;
      height = window.innerHeight;
    } else {
      height = this._el.clientHeight;
    }
  }

  const camera = new THREE.PerspectiveCamera(60, width / height, 0.01, 10000.0);

I'm just starting out, so if this explanation wasn't clear i'll explain it further, although I think this patch might not be the ideal solution.

**Comment by morsdyce** [comment]
I initially did it as you suggested, almost word for word but had some issues with passing my own camera, things didn't look right.

In the end I added a function that returns a reference to the Player instance camera

**Comment by DilipRamirez** [comment]
i'll reproduce it on a clean installation, I guess I forgot a step. Any meaningful error ?

**Comment by DilipRamirez** [comment]
@morsdyce  forgot to add the line about adding the camera to the instance initialization in client.js:
`const vr = new VRInstance(bundle, 'CentroArteVR', parent, {
    enableHotReload: true,
    scene: scene, // Custom scene
    camera: camera, // Custom camera 
    ...options,
  });`

**Comment by morsdyce** [comment]
Can't remember right now, tried lots of things that day.

It was either a black screen or it didn't sit right with the example PANO

**Comment by DilipRamirez** [comment]
the only time I had a black screen was because it need to get the width and height, so I just copied and pasted the width/height calculations done in Player.js when creating the camera. Btw do you have any idea how to use the sound module? looks like it's broken still (probably will open another thread but just in case..)

**Comment by morsdyce** [comment]
Haven't tried yet, mostly in focus of creating scene composition and VR
controllers support.

**Comment by DilipRamirez** [comment]
@morsdyce well I ran the code in my local repo at home and just by passing the camera in the VRInstance works just fine, without any patch. Would you try adding it ?

**Comment by amberroy** [comment]
yes you can pass a camera to the Player instance or use Player.camera to get the default one that is created, and I agree it would be convenient to have these options on the VRInstance as well.

**Comment by amberroy** [comment]
Both 1 & 2 above are implemented. Added VRInstance.camera() to get current camera.  Can also pass camera in the options to VRInstance  constructor

**Comment by copypasteearth** [comment]
when I try to use VrInstance.camera() to get a camera it says that cannot read property camera from undefined, any help?
