### ISSUE TITLE
Cube sample with three.js not working

### ISSUE THREAD

**Issue by krzysztofGwozdz** [facebookincubator/react-vr#45]
### Description

I will try three.js in ReactVR so first of all I want run your Cube Sample in my project to see how it works. I have made all the same as you in the sample but finally I have some errors in the console and nothing to see on the screen.

#### Logs

`GET http://localhost:8081/vr/client.bundle?platform=vr localhost/:14`
`GET http://localhost:8081/vr/client.bundle?platform=vr 500 (Internal Server Error) localhost/:14` 
`Uncaught ReferenceError: ReactVR is not defined
    at (index):17`

### Reproduction

Here is my index.html:

>   <html>
    <head>
      <title>Krzysztof Gwóźdź | Portfolio</title>
      <style>body { margin: 0; }</style>
    <head>
    <body>
      
      <script src="./client.bundle?platform=vr"></script>
      <script>
        // Initialize the React VR application
        ReactVR.init(
          // When you're ready to deploy your app, update this line to point to
          // your compiled index.bundle.js
          '../index.vr.bundle?platform=vr&dev=true',
          // Attach it to the body tag
          document.body
        );
      </script>
    </body>
  </html>

and client.js:

>    
      import {VRInstance} from 'react-vr-web';
      import {Module} from 'react-vr-web';
      import * as THREE from 'three';

      function init(bundle, parent, options) {
        const scene = new THREE.Scene();
        const cubeModule = new CubeModule();

        const vr = new VRInstance(bundle, 'Portfolio', parent, {
          // Add custom options here
          cursorEnabled: true,
          cursorVisibility: 'visible';
          nativeModules: [ cubeModule ],
          scene: scene,
        });

        const cube = new THREE.Mesh(
          new THREE.BoxGeometry(1, 1, 1),
          new THREE.MeshBasicMaterial(),
        );
        cube.position.z = -4;
        scene.add(cube);

        cubeModule.init(cube);

        vr.render = function(timestamp) {
          // Any custom behavior you want to perform on each frame goes here
          const seconds = timestamp / 1000;
          cube.position.x = 0 + (1 * (Math.cos(seconds)));
          cube.position.y = 0.2 + (1 * Math.abs(Math.sin(seconds)));
        };
        // Begin the animation loop
        vr.start();
        return vr;
      };

      export default class CubeModule extends Module {
        constructor() {
          super('CubeModule');
        }

        init(cube) {
          this.cube =  cube;
        }

        changeCubeColor(color) {
          this.cube.material.color = new THREE.Color(color);
        }
      }

      window.ReactVR = {init};
### Additional Information

* react-vr package version: 0.1.0
* react-vr-web package version: 0.1.0
* Operating System: MacOS X El Capitan 10.11.6
* Graphics Card: Intel Iris 1536  MB
* Browser: Chrome 55.0.2883.95 (64-bit)

I would be thankful for your help.

**Comment by DilipRamirez** [comment]
I created a blank project and tried to reproduce what you had, and the project worked just fine. Would you share index.vr.js please? Thanks !

**Comment by gilekpl** [comment]
Thank for your response!

My index.vr.js is almost blank, because I made few components. I'm pasting below.


index.vr.js
>  
    import React from 'react';
    import {AppRegistry} from 'react-vr';
    import Layout from './js/components/Layout';

    AppRegistry.registerComponent('Portfolio', () => Layout);

Layout.js:
>
    import React from 'react';
    import {
      asset,
      Pano,
      Text,
      View,
      Animated,
      Easing,
    } from 'react-vr';

    import Line from './Line';
    import Name from './Name';
    import Title from './Title';
    import CubeSample from './CubeModule';

    export default class Layout extends React.Component {
      constructor(props) {
        super(props);

        this.state = {
          headerAnim: new Animated.Value(-10),
          headerAnimY: new Animated.Value(0),
        };
      }

      componentDidMount() {
        Animated.timing(
            this.state.headerAnim,
            {toValue: -20, duration: 300, delay: 2000,}
          ).start();
        Animated.timing(
            this.state.headerAnimY,
            {toValue: 12, duration: 300, delay: 2000,}
          ).start();
      }

      render() {
        return (
          <View>
            <View>
              <Pano source={asset('chess-world_1.jpg')}/>
            </View>
            <Animated.View
              style={{
                transform: [{translateZ: this.state.headerAnim},
                            {translateY: this.state.headerAnimY}]
              }}>
              <Line />
              <Name />
              <Title />
              <CubeSample />
            </Animated.View>
          </View>
        );
      }
    };

CubeModule.js:
>
    import React from 'react';
    import NativeModules from 'react-vr'
    import {
      StyleSheet,
      Text,
      View,
      Animated,
      Easing,
    } from 'react-vr';

    const CubeModule = NativeModules.CubeModule;

    export default class CubeSample extends React.Component {
      constructor(props) {
        super(props);
        this.state = {btnColor: 'white', cubeColor: 'yellow'};
        CubeModule.changeCubeColor(this.state.cubeColor);
      }

      render() {
        return (
            <VrButton
              style={{
                backgroundColor: this.state.btnColor,
                borderRadius: 0.05,
                margin: 0.05,
              }}
              onEnter={()=>{this.setState({btnColor: this.state.cubeColor})}}
              onExit={()=>{this.setState({btnColor: 'white'})}}
              onClick={()=>{
                let hexColor = Math.floor(Math.random()*0xffffff).toString(16);
                // Ensure we always have 6 digits by padding with leading zeros.
                hexColor = '#'+(('000000'+hexColor).slice(-6));
                this.setState({cubeColor: hexColor, btnColor: hexColor});
                // Asynchronous call to custom native module; sends the new color.
                CubeModule.changeCubeColor(hexColor);
              }}>
              <Text style={{
                fontSize: 0.15,
                paddingTop: 0.025,
                paddingBottom: 0.025,
                paddingLeft: 0.05,
                paddingRight: 0.05,
                textAlign:'center',
                textAlignVertical:'center',
              }}>
                button
              </Text>
            </VrButton>
          </View>
        );
      }
    };

**Comment by amberroy** [comment]
Since the CubeSample worked before your modifications, I'd recommend applying your changes one-by-one, testing each time, to isolate what is causing the issue.

**Comment by migmacdev** [comment]
The issue was caused for a misplaced semmicolon, after the cursorVisibility: 'visible'; line in client.js file, use comma instead
