### ISSUE TITLE
[Slack] Unofficial React-vr slack!

### ISSUE THREAD

**Issue by DilipRamirez** [facebookincubator/react-vr#46]
### Description

While there is a WebVR Slack (webvr.slack.com) I think it would be a good idea to form a community around react-vr to help it grow ! Request an invitation here (I'm still figuring out how to enable invitation requests) and join me at [Unofficial ReactVR](https://unofficialreactvr.slack.com) !

**Comment by amberroy** [comment]
Thank you for sharing!

**Comment by DilipRamirez** [comment]
Thank you for releasing this awesome project! I tweeted you yesterday about the audio module, where can I share the files? Should I create a thread in this repo?

**Comment by tomaszlakomygp** [comment]
Hey, can I get an invite too? :)

**Comment by DilipRamirez** [comment]
Yup! Just let me get Slackin to automate the invitation proccess, should be done by tomorrow, i'll post the link here.

**Comment by JuanDelgadillo** [comment]
This is great, I would like to be part of this slack too 😃

**Comment by Jickelsen** [comment]
I'd like an invite too. Thanks in advance!

**Comment by morenoh149** [comment]
@DilipRamirez you must setup a slack self inviter https://github.com/fateyan/Slack-Inviter or similar and lock this thread. I've seen these threads on github in the past and it gets very annoying to see a continuous flow of invite requests.

**Comment by DilipRamirez** [comment]
@morenoh149  yup, I was setting up Slackin on Now but it seems that the deployment script is broken. Unfortunaly for today I have no time to fix it, but i'll see what I can do to make it work. Thanks for the link!

**Comment by DilipRamirez** [comment]
Okay people, the invitations are open! Check https://unofficialreactvr.herokuapp.com/ . Since it's new expect a slow start, but hopefully we can make a community out of it. @morenoh149 @amberroy @Jickelsen @JuanDelgadillo @tomaszlakomygp be my guests :-P

**Comment by morenoh149** [comment]
lock the thread please
