### ISSUE TITLE
OVRAudio - RCTAudioModule

### ISSUE THREAD

**Issue by DilipRamirez** [facebookincubator/react-vr#47]
### Description

So at first I was trying to use the audio module provided by you, but turns out it didn't work quite well. I spent some time working on it and now it supports 2D Audio using the WebAudio API. I think the most important issue about the code is that it tried to play the file even when it wasn't even loaded (since it was an asynchronous call), that and the fact that I wasn't able to make it work on custom components. 

### Solution

After spending some time digging through the source code I came with the solution to add an AudioSampleLoader (which I borrowed from https://github.com/ScottMichaud/AudioSampleLoader) and integrated it with the existing VRAudioBufferSource. That and a few methods and private functions here and there, which you can see here https://github.com/DilipRamirez/custom-ovr-audio (if is there any better way to share the code, like a fork or something, I would be happy to republish it). 
Also, I introduced some Promises, but looking back i'm not so sure whether it is actually necessary. 

But the code works haha.

Thank you and hopefully this code helps in development!

**Comment by amberroy** [comment]
Thank  you for sharing!
