### ISSUE TITLE
Documentation links to edit on github do not work

### ISSUE THREAD

**Issue by tomaszlakomygp** [facebookincubator/react-vr#48]
### Description
I'm preparing a talk for a local meetup about React VR and I've noticed some typos in the documentation that I wanted to fix. I've noticed that there's a handy link on bottom of each page:

![screen shot 2017-02-02 at 17 03 30](https://cloud.githubusercontent.com/assets/16646517/22557059/8c0a46ce-e969-11e6-9092-c9ab4454c68b.png)

Unfortunately all links of this type are redirecting me to a 404 page.

#### Expected behavior
A documentation reader should be able to propose fixes for typos etc. (since it's an open source project)
#### Actual behavior
All aforementioned links take the reader to a 404 page.

#### Logs
N/A

### Reproduction

N/A

### Solution
I'm not sure whether the site is actually supposed to be open source so I'd rather not recommend anything. If it's in fact open source - I'd be happy to help :)

### Additional Information
N/A

**Comment by amberroy** [comment]
It is not possible to edit the docs online or make a pull request, as we are not open-source yet.  However we will fix that link to point to this Issues board, where you can report typos or errors.  I can imaging it's discouraging to get a 404 when you are trying to contribute!  thanks for your  persistence!

**Comment by tomaszlakomygp** [comment]
No worries, thanks for the reply :)

**Comment by amberroy** [comment]
docs updated!
