### ISSUE TITLE
(REQUEST) I'd like to get involved in dev for this project

### ISSUE THREAD

**Issue by mannyhenri** [facebookincubator/react-vr#49]
FYI love the template when creating the issue. This is primarily a request to get involved as I'm a LinkedIn/Lynda author and we're planning a course on VR with React in August. Would love to be able to get enough ground work with this and plan the course accordingly.

**Comment by amberroy** [comment]
Great to hear this!  Will get back to you shortly with more info.

**Comment by amberroy** [comment]
We are not yet accepting PRs for the React VR framework.  Nonetheless, you can definitely be involved building apps using React VR, which is why we make this preview release before going Open Source, to get feedback from devs and see what you build!

**Comment by koktingfeng** [comment]
Hello Manny, you still own us many outstanding items from our previous project. Please give me an answer ASAP

**Comment by koktingfeng** [comment]
Hi Manny, I will not stop checking back in until you have delivered what you promised. Please check our contract, you are obliged to deliver 50% of the items, including the codes that you're supposed to refactor.
