### ISSUE TITLE
Watchman fails: "Error watching file for changes"

### ISSUE THREAD

**Issue by jbreckmckye** [facebookincubator/react-vr#54]
### Description

I'm not able to run the samples locally (OSX Sierra). This is despite running `brew install --HEAD watchman`, as per the resolution of a [similar issue](https://github.com/facebookincubator/react-vr/issues/23) three months ago.

#### Expected behavior

I'm able to kick off the application with `npm start` and browse the samples on localhost.

#### Actual behavior

Alack! The file watcher explodes - even after manually installing watchman via `brew`.

#### Logs

```
ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1023:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1283:11)

...

npm ERR! @ start: `node node_modules/react-native/local-cli/cli.js start --root .`
npm ERR! Exit status 11
npm ERR! 
npm ERR! Failed at the @ start script 'node node_modules/react-native/local-cli/cli.js start --root .'.
```

#### Environment details

* react-vr package version: preview package
* Operating System: OS X Sierra

**Comment by andrewimm** [comment]
Hey @jbreckmckye 

Sorry you're hitting this error. Since the packaging server is actually part of the react-native package, I'd recommend that you take your issues to github.com/facebook/react-native and see if they can help you resolve it.
