### ISSUE TITLE
[QUESTION] How to move in a scene? 

### ISSUE THREAD

**Issue by nicolasgere** [facebookincubator/react-vr#56]
Hello, for a project, i try to move in a scene using keyboard, but i didnt found any way to configure that, what should i do? Is it a simple way to move the camera using keyboard.
Is the controls will works by default if i use a headset or occulus?

A solution i use, is to move the camera each frame when a key is press. Is it something  wrong?
Thanks a lot for that jobs ! I Can't wait to do some pr

**Comment by nicolasgere** [comment]
Finnaly i understand how it's work, sorry for that. Everything happen with the controller camera etc

**Comment by rvetere** [comment]
hi there - i try to achieve the same but i totally don't know how.... i'm already stuck to properly attach a key-event listener... could you share some example code how you achieved it? 😉

**Comment by steverob** [comment]
@nicolasgere could you share what you learned please? Thanks.

**Comment by breadadams** [comment]
For anyone looking to _"move the camera"_ (the users point of view), the current solution is using the [`<Scene>`](https://facebook.github.io/react-vr/docs/scene.html) component and the `translate` style prop, eg.:

```
<Scene style={{
  transform: [
    {translate: [-2, 5, -5]}
  ]
}}>
  <Pano source={asset('chess-world.jpg')}/>
</Scene>
```
