### ISSUE TITLE
server is not working

### ISSUE THREAD

**Issue by Mudin** [facebookincubator/react-vr#6]
Hello,

This seems really awesome framework!
I would like to see some demo or sample project.
But I cannot check the my project on the browser.
Starting server has some issue, it cannot watch or sth.
I got the following log:

![screen shot 2016-12-15 at 12 21 48 pm](https://cloud.githubusercontent.com/assets/15241252/21210879/20b2bc3a-c2c2-11e6-8053-e197e7445526.png)

Please, help to figure this out.

Thank you
Best regards,

Mudin

### Additional Information

* react-vr package version: 2.15.1
* react-vr-web package version: 2.15.1
* Operating System: MacOS
* Graphics Card: Intel Iris Pro 1536 MB
* Browser: Chrome 54.0.2840.98 (64-bit)
* VR Device: Google Cardboard

**Comment by andrewimm** [comment]
We use the packaging server from React Native, so you should follow up there. It looks like this thread contains a number of potential fixes: https://github.com/facebook/react-native/issues/10028

**Comment by ericvicenti** [comment]
cc @cpojer

**Comment by Mudin** [comment]
Thank you,
I tried to follow there, but no luck
