### ISSUE TITLE
ReactVR is undefined 

### ISSUE THREAD

**Issue by RohanDamani** [facebookincubator/react-vr#61]
I'm getting an error when trying to run the react-vr preview samples.  The client.bundle?platform=vr is not getting created.  Please help!

```
GET http://localhost:8081/samples/CubeSample/vr/client.bundle?platform=vr 
Uncaught ReferenceError: ReactVR is not defined
    at (index):11
```

`    
    <script src="./client.bundle?platform=vr"></script>`

`exports.assetExts =  [
  'bmp', 'gif', 'jpg', 'jpeg', 'png', 'psd', 'svg', 'webp', // Image formats
  'm4v', 'mov', 'mp4', 'mpeg', 'mpg', 'webm', // Video formats
  'aac', 'aiff', 'caf', 'm4a', 'mp3', 'wav', // Audio formats
  'html', 'pdf', // Document formats
];

exports.moduleSystem = require.resolve('./react-packager/src/Resolver/polyfills/require.js');

exports.platforms = ['ios', 'android', 'vr', 'windows', 'web'];

exports.polyfills = [
  require.resolve('./react-packager/src/Resolver/polyfills/polyfills.js'),
  require.resolve('./react-packager/src/Resolver/polyfills/console.js'),
  require.resolve('./react-packager/src/Resolver/polyfills/error-guard.js'),
  require.resolve('./react-packager/src/Resolver/polyfills/Number.es6.js'),
  require.resolve('./react-packager/src/Resolver/polyfills/String.prototype.es6.js'),
  require.resolve('./react-packager/src/Resolver/polyfills/Array.prototype.es6.js'),
  require.resolve('./react-packager/src/Resolver/polyfills/Array.es6.js'),
  require.resolve('./react-packager/src/Resolver/polyfills/Object.es7.js'),
  require.resolve('./react-packager/src/Resolver/polyfills/babelHelpers.js'),
];

exports.providesModuleNodeModules = [
  'react-native',
  'react-native-windows',
  // Parse requires AsyncStorage. They will
  // change that to require('react-native') which
  // should work after this release and we can
  // remove it from here.
  'parse', 'react-vr', 'react-vr', 'react-vr', 'react-vr',
];

exports.runBeforeMainModule = [
  // Ensures essential globals are available and are patched correctly.
  'InitializeCore',
];`

react-native-cli: 2.0.1
react-native: 0.37.0

**Comment by andrewimm** [comment]
When you attempt to load the client.bundle URL directly in your browser, what does it return?

Does your packaging server echo any errors to your terminal?
