### ISSUE TITLE
[Question] Custom Vertex/Fragment Shaders

### ISSUE THREAD

**Issue by timoxley** [facebookincubator/react-vr#64]
Is it possible to use custom vertex or fragment shaders with react-vr? If so, how? And how does that even work? Does react-vr render VR using native apis or is it using a webview + a webgl canvas?  I don't understand how react-vr seems to support running threejs across multiple platforms. Thanks.

**Comment by amberroy** [comment]
you're right threejs doesn't exactly run across multiple platforms, it runs in the web browser, using the WebGL canvas, and its the web browser that runs across multiple platforms (desktop and mobile).  React VR runs in the web browser and uses three.js as its 3D graphics engine.  You could write a custom React VR component that uses shaders, although we don't have any examples of that yet.  Did you have a particular application or example in mind?

**Comment by timoxley** [comment]
Awesome, that clears it up, thanks.

> Did you have a particular application or example in mind?

Not particularly, I just wanted to know if there were compatibility limitations to be aware of.

I think it might be worthwhile having a short explainer in the readme about **how react-vr works** and exactly what it's providing (in addition to a JSX interface to ThreeJS), since I was given the impression from experienced people that react-vr was doing some kind of device-native 3D rendering and that shader programming was likely to be incompatible.
