### ISSUE TITLE
<Mesh> `material` not defined ReferenceError

### ISSUE THREAD

**Issue by spikebrehm** [facebookincubator/react-vr#65]
### Description

When trying to use the `<Mesh>` component:

```js
<Mesh
  source={{ mesh: asset('porsche.obj'), texture: asset('porsche.bmp') }}
/>
```

I see the following ReferenceError about `material` not being defined:

<img width="1159" alt="screen shot 2017-03-07 at 4 32 18 pm" src="https://cloud.githubusercontent.com/assets/133937/23684474/ef5ddbc4-0353-11e7-9c76-cff1558dea03.png">

From reading the sourcemapped code, it does indeed look like `material` is not defined in the `_loadOBJ()` method.

#### Expected behavior

No ReferenceError.

#### Actual behavior

ReferenceError.

### Reproduction

A mesh like:

```js
<Mesh
  source={{ mesh: asset('porsche.obj'), texture: asset('porsche.bmp') }}
/>
```

Using this 3D model:
http://tf3dm.com/3d-model/porsche-911-gt-43465.html

### Solution

The constructor of `RCTMesh` defines a local `material` variable:

```js
    var material = new THREE.MeshBasicMaterial({
      wireframe: false,
      color: 'white',
      side: THREE.DoubleSide,
    });
```

One solution would be to change this to be an instance property:

```js
    this.material = new THREE.MeshBasicMaterial({
      wireframe: false,
      color: 'white',
      side: THREE.DoubleSide,
    });
```

Which could then be referenced in `_loadOBJ()` as `this.material`.

### Additional Information

```
├── react-vr@0.1.5
├── react-vr-web@0.1.4
├── three@0.80.1
└── xopen@1.0.0
```

**Comment by andrewimm** [comment]
This was recently fixed in master, and should be rolling out in the next release.
I realized we weren't covering the texture path in our tests, which is how this slipped by us after a recent restructure. That should all be resolved now as well.

**Comment by spikebrehm** [comment]
Thanks!

**Comment by tatyramirezgmj** [comment]
Hi I have the same issue  
```    <Mesh
          source={{
            mesh: asset('./stage_obj/stage_obj.obj'),
            mtl: asset('./stage_obj/stage_obj.mtl')
          }}style={{
            transform: [{ translate: [ -10, -8, 20 ]}, {scale: 0.02},
            {rotateX : 0}, {rotateY: 120}, {rotateZ:0}]
          }}
        />
``` 
and this is what I get 
<img width="730" alt="screen shot 2017-07-25 at 1 13 28 pm" src="https://user-images.githubusercontent.com/21221368/28584548-21fed0b0-713b-11e7-8641-e20d25fc12b6.png">

**Comment by andrewimm** [comment]
@tatyramirezgmj what is the actual error you get? can you provide a stack trace? What version of react-vr are you using?

At the location of your breakpoint, material should not be defined yet, so that is expected.

**Comment by tatyramirezgmj** [comment]
https://www.turbosquid.com/3d-models/stage-3d-model/853588 this is the model that I'm using. And I'm using version Version 0.3.5

**Comment by andrewimm** [comment]
You'll need to a recent version of React VR, the fix mentioned in this issue didn't get released until a later version. Anything before v1.0.0 is a developer preview and is unsupported, I recommend grabbing the latest (1.4.0).

Because the project layout changed slightly from 0.x.x to 1.x.x, the easiest way to upgrade is actually to create a new project (`react-vr init MyProject`), and then copy over your code changes to `index.vr.js`, `client.js`, etc.

**Comment by andrewimm** [comment]
Also, make sure your version of react-vr-cli is the latest before creating that new project, otherwise it won't really upgrade you

**Comment by tatyramirezgmj** [comment]
Thank you so much! Now everything much more sense!!!!
