### ISSUE TITLE
What's the reason why there is no Animation.Mesh?

### ISSUE THREAD

**Issue by nikgraf** [facebookincubator/react-vr#68]
This is just a question out of curiosity. There is Animation.View, Animation.Image & Animation.Text, but no Animation.Mesh. Why?

**Comment by andrewimm** [comment]
Simplest answer: because nobody's built it yet, and there was no analog from RN's Animation library.

I'm about to issue a major overhaul of the internals of Mesh, after which there might be a good opportunity to implement `Animated.Mesh`

**Comment by nikgraf** [comment]
Cool, thanks for the quick response 👏
