### ISSUE TITLE
Android & iOS build

### ISSUE THREAD

**Issue by smkamranqadri** [facebookincubator/react-vr#7]
### Description

So can we build Android & iOS app?

**Comment by mikearmstrong001** [comment]
This release is for Web, however what you construct will work in an Android or iOS browser.

If you have a GearVR you can also use [Carmel Developer Preview](https://www.oculus.com/experiences/gear-vr/1290985657630933/) which is a preview of a GearVR optimized WebVR browser

**Comment by smkamranqadri** [comment]
Thanks.
