### ISSUE TITLE
[Question] Where do I go to file typos seen in documentation

### ISSUE THREAD

**Issue by jerelmiller** [facebookincubator/react-vr#70]
### Description

I noticed a couple typos in the documentation. I wasn't sure where to file these types of things or how I could help aid in fixing them.

##### Typo #1:

Page: https://facebookincubator.github.io/react-vr/docs/getting-started.html
Under "Running the Samples"

Typo: `Navigate to the React VR Preelease preview folder.`
Fix: Should be `Prerelease`

##### Typo #2

Page: https://facebookincubator.github.io/react-vr/docs/react-vroverview.html

Under "JSX and Declarative UIs "

Typo: `The React website contains further details on JAX.`
Fix: Should be `JSX`

#### Expected behavior

N/A

#### Actual behavior

N/A

#### Logs

N/A

### Reproduction

N/A

### Solution

I would love to create a PR against the documentation to address these, but am unsure how to do this currently.

### Additional Information

N/A

**Comment by andrewimm** [comment]
Unfortunately we aren't able to do docs PRs until we release React VR and put the source code up here. Until then, issues here are probably the best way to alert us to these things. Thanks for catching this!

**Comment by jerelmiller** [comment]
Awesome! No problem! I will be on the lookup for the public release for future in case I see this. Thanks for the reply!
