### ISSUE TITLE
"Unable to resolve module" when upgrading react-vr

### ISSUE THREAD

**Issue by johnnyshankman** [facebookincubator/react-vr#72]
### Description

Bug, can't build previous project after updating to newest version.

#### Expected behavior

I `npm update` and nothing breaks.

#### Actual behavior

I `npm update` and the page no longer works. View will not import even after following the instructions given by the error log. I can't seem to debug the issue.

#### Logs

```
Unable to resolve module `View` from `/Users/john/Documents/workspace/react-vr-playground/project/node_modules/react-vr/Libraries/react-vr.js`: Module does not exist in the module map or in these directories:
  /Users/john/Documents/workspace/react-vr-playground/project/node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.
```

### Reproduction

Updated my project settings using `npm update` and resolved all dependency mismatches after hearing the `<Video>` announcement yesterday.

It could be something specific to my project but I'm unsure. `client.js` builds just fine.

### Solution

I'm unsure.

### Additional Information

* react-vr package version: 1.6
* react-vr-web package version: 1.6
* Operating System: OSX El Capitan 11.6
* Graphics Card: MBP integrated
* Browser: Anythig
* VR Device: Anything

**Comment by andrewimm** [comment]
Are you using react-native v0.42?

Did you upgrade an existing project? If so, you need to add the following to your rn-cli.config.js:

```
getPlatforms() {
    return ['vr'];
  },

  getProvidesModuleNodeModules() {
    return ['react-native', 'react-vr'];
  },
```

VR is now a fully-supported platform for React Native, and we no longer need to do a hack to monkey-patch the files.

**Comment by johnnyshankman** [comment]
@andrewimm I am!

Added that method to my `rn-cli.config.js` and we are all good now. Thank you.

```
getProvidesModuleNodeModules() {
    return ['react-native', 'react-vr'];
  },
```

**Comment by johnnyshankman** [comment]
Is there documentation somewhere from that? I might just be missing it when looking through the [v0.42 notes](https://github.com/facebook/react-native/releases/tag/v0.42.0)

**Comment by andrewimm** [comment]
It's an internal change designed to support us. It didn't occur to me that people would have problems upgrading existing projects. I'll leave this issue open so that others can find the solution.

**Comment by johnnyshankman** [comment]
Wonderful.

**Comment by andrewimm** [comment]
Note: This is only necessary for upgrading older projects. If you find this necessary with a new project, you need to update your react-vr CLI:

```
npm update -g react-vr-cli
```

As of this latest release, CLI versions are explicitly tied to specific react-vr releases, so it's not possible to get an out-of-date configuration with newer dependencies, and this should not be a problem again.
