### ISSUE TITLE
<Video> Looping

### ISSUE THREAD

**Issue by johnnyshankman** [facebookincubator/react-vr#73]
### Description

Feature Request

#### Expected behavior

When I use the new [Video](https://facebookincubator.github.io/react-vr/docs/video.html) component I expect to be able to control the looping value of the video texture.

#### Actual behavior

Video always stops after one iteration.

#### Logs

None

### Reproduction

Use the example exactly as given in the Documentation.

### Solution

There should be a prop that mirrors the behavior of `muted` and `autoplay` for `loop`.

### Additional Information

* react-vr package version: 0.1.6
* react-vr-web package version: 0.1.6
* Operating System: N/A
* Graphics Card: N/A
* Browser: All
* VR Device: Any

**Comment by amberroy** [comment]
Good point we have the `loop` for `<Sound>` but not `<Video>`, this would be useful.

**Comment by johnnyshankman** [comment]
Yeah! I'd love to have looping video textures, opens up some really interesting ideas.

**Comment by amberroy** [comment]
'loop' property is now added to Video.  Install lastest npm modules to use.  The TourSample is upgraded to use a looping video, download the Prerelease zip to run it.
