### ISSUE TITLE
Video texture fails at instance of check

### ISSUE THREAD

**Issue by Ninerian** [facebookincubator/react-vr#74]
### Description

When using the new video component, I got an exception thrown.

#### Expected behavior
Video is shown 

#### Actual behavior
No video is shown

#### Logs
```
Uncaught Error: Image textures must be of type THREE.Texture
    at UIView.setImageTexture (UIView.js:485)
    at onLoad (Video.js:67)
    at RCTVideoModule._onMediaReady (RCTVideoModule.js:75)
    at VRVideoComponent._onMediaReady (VRVideoComponent.js:73)
    at BasicVideoPlayer._onMediaReady (BasicVideoPlayer.js:24)
```

### Reproduction
- Create new project with react-vr-cli `react-vr init videotest`
- update package.json `ncu -ua && npm install`
- update rn-cli.config.js -> #72
- add video texture to view
  ```
   <Video style={{width: 3.0, height: 2.0}} source={asset('/intro.webm')}/>
  ```
- start server
- load localhost:8081/vr/

### Solution
The error occurs at line 470 in UIView.js when the texture is checked for instance of Three.texture, 
because the Texture is created with the function from `node_modules/ovr-video/node_modules/three/build/three.js` and the _ThreeShim2.default.Texture is from `/node_modules/ovrui/node_modules/three/build/three.js` the test fails. 

The solution could be a overall dependency of three.js.

### Additional Information

* react-vr package version: 0.1.6
* react-vr-web package version: 0.1.6
* Operating System: MacOS
* Graphics Card: Nvidia
* Browser: Chrome  56.0.2924.87
* VR Device: None
* NPM Version: 4.4.1
* Node Version: 4.4.7

**Comment by andrewimm** [comment]
Hmm, with npm > 3, you shouldn't have a directory at `node_modules/ovr-video/node_modules/three/`. That's likely the cause of the problem: two version of Three.js means that a Texture from one will not be an instanceof a Texture class from another.

I'll see if there's anything obvious in the project configuration that would cause this.

**Comment by andrewimm** [comment]
Also, you shouldn't have needed to run the update from #72  on a new project. If you found that necessary, you should update your react-vr-cli (`npm update -g react-vr-cli`) and try creating your project. That may be the cause for this dependency disconnect.

**Comment by Ninerian** [comment]
Okay I had a file conflict with an older version npm, but now I updated react-vr-cli to 0.1.5 and the resulting package.json contains the old versions. 

```
"dependencies": {
    "ovrui": "~0.1.0",
    "ovr-audio": "~0.1.0",
    "ovr-video": "~0.1.0",
    "react": "15.4.1",
    "react-native": "0.42.0",
    "three": "^0.80.1",
    "react-vr": "~0.1.0",
    "react-vr-web": "~0.1.0",
    "xopen": "1.0.0"
  }
```

I update them now and test the video again.

**Comment by Ninerian** [comment]
So I found the error. With updating all dependencies via ncu I also updated three.js to the latest. As the ovr-ui and ovr-video depending on 80.1 they used their own node_modules folder. 

Now its working like a charm. 👍
