### ISSUE TITLE
One problem in the "getting-started" document

### ISSUE THREAD

**Issue by yofine** [facebookincubator/react-vr#75]
### Description

I found a small issue when I read the [getting-started]( https://facebookincubator.github.io/react-vr/docs/getting-started.html). The “Running the Samples“ paragraph didn’t say where `React VR Prerelease` came from. Later, I found the answer from Github README.md which is `download the React VR Prerelease.zip from Oculus`. I think other new people may also have such trouble.

### Solution

I was going to submit a PR to fix the problem, But I learned from other issues that the documents are generated from md files. 

### One more thing
I am also a fan of react and webvr, When I found ReactVR, it's amazing. Thanks for creating such a cool thing. I and my friends are translating [ReactVR's Chinese documents](http://webvrcn.org/react-vr/#/), hoping to share so cool technology with more people :D

**Comment by amberroy** [comment]
Agree the link should be in there, we'll add it.  

wow I think this is the first translation!  thanks for letting us know.

**Comment by amberroy** [comment]
@larrylin28

**Comment by yofine** [comment]
Cool, thanks for the response

**Comment by larrylin28** [comment]
One thing I'd suggest to change in the translation:
<img width="416" alt="screen shot 2017-03-16 at 3 33 44 pm" src="https://cloud.githubusercontent.com/assets/7868041/24005286/7e166df0-0a60-11e7-8b66-9afedcedcf55.png">

**Comment by yofine** [comment]
@larrylin28  Oh thanks. Are you chinese?

**Comment by yofine** [comment]
@larrylin28 The project has just begun and I will follow up on the technical and grammar review
