### ISSUE TITLE
Swap locations for Prev/Next links.

### ISSUE THREAD

**Issue by gabejohnson** [facebookincubator/react-vr#8]
### Description
The Next & Prev links are reversed in the docs. I keep pointing to the lower right to go to next.

#### Expected behavior
Prev link is in the lower left and Next link is in the lower right.

#### Actual behavior
This is reversed.

### Solution
Copy changes from https://github.com/facebook/react-native/pull/10753

### Additional Information

* react-vr package version: 0.1.1
* react-vr-web package version: 0.1.1

**Comment by gabejohnson** [comment]
Looks like this is a duplicate of https://github.com/facebookincubator/react-vr/issues/2. Closing.

**Comment by mikearmstrong001** [comment]
fixed in online docs
https://facebookincubator.github.io/react-vr
