### ISSUE TITLE
Creating project with dashes-in-the-name

### ISSUE THREAD

**Issue by Fasani** [facebookincubator/react-vr#9]
### Description

I took the download zip and followed the guide on GitHub.
I created a project with-dashes-in-the-name and this causes some issues.

GET http://localhost:8081/index.vr.bundle?platform=vr&dev=true 500 (Internal Server Error)
blob:http://localhost:8081/c99b3411-b198-4719-9856-553bedb0999a:18 DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8081/index.vr.bundle?platform=vr&dev=true' failed to load.
    at onmessage (blob:http://localhost:8081/c99b3411-b198-4719-9856-553bedb0999a:15:7)

#### Expected behavior
I expect to be alerted that my name should not use dashes or allow dashes.

#### Actual behavior
Project breaks.

### Reproduction
react-vr init PROJECT-NAME-WITH-DASHES

### Solution

Don't use names with dashes.

### Additional Information
I ran the project without dashes in the name and it worked, I was able to view the demo in my HTC Vive, it's truly magic. This is really exciting stuff, to be able to send links to VR spaces/sites and experience them on the HMD is a game changer.

* react-vr package version:
    "version": "0.0.1",
* react-vr-web package version:
    "react-vr": "~0.1.0",
    "react-vr-web": "~0.1.0"

* Operating System: Windows 10
* Graphics Card: NVidia
* Browser: Chrome
* VR Device: Vive

**Comment by andrewimm** [comment]
I have fix ready for this, it should go out in CLI v0.1.2, which I will attempt to publish this evening.

**Comment by andrewimm** [comment]
Sorry for the delay, 0.1.2 CLI has been published.

**Comment by andrewimm** [comment]
Sorry for the delay, 0.1.2 CLI has been published.
